/*
  DO NOT MODIFY - This file has been generated by https://github.com/flemay/Semantic-UI-Meteorize
*/

Package.describe({
  name: 'funyx:semantic-ui',
  version: '2.4.1',
  summary: 'Official Semantic UI Integration for Meteor',
  git: 'https://github.com/funyx/Semantic-UI-Meteor.git',
  documentation: 'README.md'
});

Package.registerBuildPlugin({
  name: "generateSemanticUi",
  use: [
    'ecmascript@0.1.5',
    'ejson@1.0.6',
    'funyx:semantic-ui-data@2.4.1'
  ],
  sources: [
    'semantic-ui.js',
    'data/definitions-data.js',
    'data/themes-data.js',
    'data/sites-data.js',
    'data/custom-semantic-data.js',
    'plugins/file-handler.js',
    'plugins/definitions-generator.js',
    'plugins/themes-generator.js',
    'plugins/sites-generator.js',
    'plugins/custom-semantic-json-generator.js',
    'plugins/generator.js'
  ],
  npmDependencies: {
    "lodash": "3.6.0",
    "diff": "1.3.2"
  }
});

Package.onUse(function (api) {
  api.use('isobuild:compiler-plugin@1.0.0');
});
